const SHAREPOINT_ROOT = 'https://travelcounsellorsdirectory.sharepoint.com/sites';

export const TC_HUBS = [
    {
        name: 'TCTV',
        slug: 'tctv',
        description: 'Travel Counsellors TV - Video content en updates',
        icon: '📺',
        sharePointUrl: `${SHAREPOINT_ROOT}/TCTV`,
    },
    {
        name: 'Vimeo',
        slug: 'vimeo',
        description: 'Video bibliotheek',
        icon: '🎬',
        sharePointUrl: `${SHAREPOINT_ROOT}/Vimeo`,
    },
    {
        name: 'BD Kanaal',
        slug: 'bd-kanaal',
        description: 'Business Development kanaal',
        icon: '📊',
        sharePointUrl: `${SHAREPOINT_ROOT}/BDKanaal`,
    },
    {
        name: 'TC Catch Up',
        slug: 'tc-catch-up',
        description: 'Laatste nieuws en updates',
        icon: '📰',
        sharePointUrl: `${SHAREPOINT_ROOT}/TCCatchUp`,
    },
    {
        name: 'Crisis Hub',
        slug: 'crisis-hub',
        description: 'Crisis management en procedures',
        icon: '🚨',
        sharePointUrl: `${SHAREPOINT_ROOT}/CrisisHub`,
    },
    {
        name: 'Marketing Hub',
        slug: 'marketing-hub',
        description: 'Marketing materialen en campagnes',
        icon: '📢',
        sharePointUrl: `${SHAREPOINT_ROOT}/MarketingHub`,
    },
    {
        name: 'Performance Hub',
        slug: 'performance-hub',
        description: 'Performance metrics en analytics',
        icon: '📈',
        sharePointUrl: `${SHAREPOINT_ROOT}/PerformanceHub`,
    },
    {
        name: 'Commercial Hub',
        slug: 'commercial-hub',
        description: 'Commerciële informatie',
        icon: '💼',
        sharePointUrl: `${SHAREPOINT_ROOT}/CommercialHub`,
    },
    {
        name: 'Events Hub',
        slug: 'events-hub',
        description: 'Evenementen en activiteiten',
        icon: '🎉',
        sharePointUrl: `${SHAREPOINT_ROOT}/EventsHub`,
    },
    {
        name: 'IATA Hub',
        slug: 'iata-hub',
        description: 'IATA informatie en certificering',
        icon: '✈️',
        sharePointUrl: `${SHAREPOINT_ROOT}/IATAHub`,
    },
    {
        name: 'IT Hub',
        slug: 'it-hub',
        description: 'IT support en technische informatie',
        icon: '💻',
        sharePointUrl: `${SHAREPOINT_ROOT}/ITHub`,
    },
    {
        name: 'Corporate Hub',
        slug: 'corporate-hub',
        description: 'Corporate informatie en beleid',
        icon: '🏢',
        sharePointUrl: `${SHAREPOINT_ROOT}/CorporateHub`,
    },
    {
        name: 'TC Care',
        slug: 'tc-care',
        description: 'Zorg en welzijn',
        icon: '❤️',
        sharePointUrl: `${SHAREPOINT_ROOT}/TCCare`,
    },
    {
        name: 'TC Support',
        slug: 'tc-support',
        description: 'Support en hulp',
        icon: '🆘',
        sharePointUrl: `${SHAREPOINT_ROOT}/TCSupport`,
    },
    {
        name: 'DE&I Hub',
        slug: 'dei-hub',
        description: 'Diversity, Equity & Inclusion',
        icon: '🌈',
        sharePointUrl: `${SHAREPOINT_ROOT}/DEIHub`,
    },
    {
        name: 'Training Hub',
        slug: 'training-hub',
        description: 'Training en ontwikkeling',
        icon: '🎓',
        sharePointUrl: `${SHAREPOINT_ROOT}/TrainingHub`,
    },
    {
        name: 'Intranet',
        slug: 'intranet',
        description: 'Algemeen intranet',
        icon: '🌐',
        sharePointUrl: `${SHAREPOINT_ROOT}/Intranet`,
    },
] as const;

export type TCHub = typeof TC_HUBS[number];
